To be delivered/Source Code/Controllers/DoctorController.cs
using Ain_Shams_Hospital.Data;
using Ain_Shams_Hospital.Data.Entities;
using Ain_Shams_Hospital.ViewModels.DoctorVM;
using HospitalManagementSystem.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ain_Shams_Hospital.Controllers
{
   
    [CheckXActionFilterAttribute]
    public class DoctorController : Controller
    {
        private readonly HospitalDbContext _auc;
        // private readonly IHospitalRepository _repository;
        public DoctorController(HospitalDbContext auc)
        {
            _auc = auc;
        }

        [HttpGet]
        public IActionResult PatientFollowUp()
        {
            // int patient_id =(int) TempData["p_id"];
            int Follow_up_Id = (int)HttpContext.Session.GetInt32("Follow_up_Id");
            int patient_id = (int)_auc.Follow_Ups.Where(d => d.Id == Follow_up_Id)
                                            .Select(d => d.Patient_Id)
                                            .Single();
            var result = _auc.Patients
                .Where(O => O.Id == patient_id)
                .Select(I => new Patient { Name = I.Name, Phone = I.Phone, Medical_Record = I.Medical_Record, Health_Progress = I.Health_Progress })
                .ToList();

           var regestration_id = _auc.Patients.Include(o => o.Registration)
                .Where(O => O.Id == patient_id)
                .ToList();
            var mail = regestration_id[0].Registration.Email;
            int Doctor_Reg_Id = (int)HttpContext.Session.GetInt32("User_Reg_Id");
            int Doctor_Id = _auc.Staff
                .Where(d => d.Registration_Id == Doctor_Reg_Id)
                .Select(d => d.Id)
                .Single();
            //&& d => d.Staff_Id == Doctor_Id
            var status = _auc.Follow_Ups
                .Where(d => d.Id == Follow_up_Id)
                .Select(d => d.Status)
                .Single();
            //var status  
            ViewBag.data1 = result;
            ViewBag.data3 = mail;
            ViewBag.status = status;
            return View();
        }

        [HttpPost]
        public IActionResult PatientFollowUp(PatientFollowUpVM obj)
        {
            int Follow_up_Id = (int)HttpContext.Session.GetInt32("Follow_up_Id");
            int patient_id = (int)_auc.Follow_Ups.Where(d => d.Id == Follow_up_Id)
                                            .Select(d => d.Patient_Id)
                                            .Single();
            int Doctor_Reg_Id = (int)HttpContext.Session.GetInt32("User_Reg_Id");
            int Doctor_Id = _auc.Staff
                .Where(d => d.Registration_Id == Doctor_Reg_Id)
                .Select(d => d.Id)
                .Single();
            Patient patient;
            Follow_Up follow_Up;
            follow_Up = _auc.Follow_Ups.Where(d => d.Id == Follow_up_Id).FirstOrDefault();
            patient = _auc.Patients.Where(i => i.Id == patient_id).FirstOrDefault();
            patient.Medical_Record = patient.Medical_Record + " " + obj.Medical_Record;
            if (obj.Health_Progress != 0)
                patient.Health_Progress = obj.Health_Progress;
            if (obj.Status!= null)
                follow_Up.Status = obj.Status;
            _auc.SaveChanges();
            ModelState.Clear();

            var result = _auc.Patients
                 .Where(O => O.Id == patient_id)
                 .Select(I => new Patient { Name = I.Name, Phone = I.Phone, Medical_Record = I.Medical_Record, Health_Progress = I.Health_Progress })
                 .ToList();


            var regestration_id = _auc.Patients.Include(o => o.Registration)
                .Where(O => O.Id == patient_id)
                 .ToList();
            var mail = regestration_id[0].Registration.Email;
            var status = _auc.Follow_Ups
                .Where(d =>  d.Id == Follow_up_Id)
                .Select(d => d.Status)
                .Single();
            ViewBag.data1 = result;
            ViewBag.data3 = mail;
            ViewBag.status = status;
            return View();
        }
        public IActionResult Transfer()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Emergency()
        {
            var result = _auc.Blood_Units
                .Select(I => new Blood_Unit { Type = I.Type, Amount = I.Amount})
                .ToList();
            ViewBag.Blood_Units = result;
            var facility = _auc.Hospital_Facilities
                .Where(i => i.Type.Substring(0, 13) == "Emergency bed")
                .Select(n => new Hospital_Facility { Type = n.Type, Available = n.Available,
                    Start_Working_Hour =n.Start_Working_Hour, End_Working_Hour=n.End_Working_Hour   })
                .ToList();
            ViewBag.Hospital_Facility = facility;
            return View();
        }

        [HttpPost]
        public IActionResult Main(MainVM m, string sort, string search)
        {
            if (m.P_Id != 0)
            {
                HttpContext.Session.SetInt32("Follow_up_Id", m.P_Id);
                return Redirect("/Doctor/PatientFollowUp");
            }

            if (!string.IsNullOrEmpty(search))
            {
                TempData["SearchItem"] = m.Search_Item;

            }
            if (!string.IsNullOrEmpty(sort))
            {
                TempData["SortItem"] = m.Sort_Item;
                TempData["OrderItem"] = m.Order_Item;
            }

            return Redirect("/Doctor/Main");
        }

        [HttpGet]
        public IActionResult Main()
        {
            int Doctor_Reg_Id = (int)HttpContext.Session.GetInt32("User_Reg_Id");
            if(Doctor_Reg_Id == 0) return Redirect("/Home/Index");

            int Doctor_Id = _auc.Staff
                .Where(d => d.Registration_Id == Doctor_Reg_Id)
                .Select(d => d.Id)
                .Single();

            var Patients_FollowUps = _auc.Follow_Ups
                .Where(d => d.Staff_Id == Doctor_Id)
                .Select(p => new { p.Patient_Id, p.Id })
                .ToList();

            List<Patient> patient = new List<Patient>();
            List<Follow_Up_History> follow_up = new List<Follow_Up_History>();
            var patient_join_follow_up = new List<Tuple<Patient, Follow_Up_History>>();
            int i = 0;
            foreach (var _P in Patients_FollowUps)
            {
                patient.Add(_auc.Patients
                   .Include(p => p.Transfer_Hospital)
                   .Where(p => p.Id == _P.Patient_Id)
                   .Single());
               

                follow_up.Add(_auc.Follow_Ups_History
                .Include(f => f.Follow_Up_Type)
                .Include(f => f.Follow_Up)
                .Where(f => f.Follow_Up_Id == _P.Id)
                .Single());
                
                patient_join_follow_up.Add(new Tuple<Patient, Follow_Up_History>(patient[i], follow_up[i]));
                ++i;
            }

            var searchString = TempData["SearchItem"]?.ToString();
            if (searchString != null)
            {
                ViewBag.follow_ups = (List<Tuple<Patient, Follow_Up_History>>)patient_join_follow_up.Where(s => s.Item1.Id.ToString().Contains(searchString) || s.Item1.Name.Contains(searchString)
                || s.Item2.Follow_Up_Type.Name.Contains(searchString))
                    .ToList();
                return View();
            }

            patient_join_follow_up = (List<Tuple<Patient, Follow_Up_History>>)patient_join_follow_up.
                        OrderByDescending(s => s.Item2.Date).ToList();

            var sortString = TempData["SortItem"]?.ToString();
            if (sortString != null)
            {
                var orderString = TempData["OrderItem"] == null? "DSC": TempData["OrderItem"].ToString();
                switch ((sortString, orderString))
                {
                    case ("Date", "DSC"):
                        patient_join_follow_up = (List<Tuple<Patient, Follow_Up_History>>)patient_join_follow_up
                            .OrderByDescending(s => s.Item2.Date)
                            .ToList();
                        break;
                    case ("Date", "ASC"):
                        patient_join_follow_up = (List<Tuple<Patient, Follow_Up_History>>)patient_join_follow_up
                            .OrderBy(s => s.Item2.Date)
                            .ToList();
                        break;
                    case ("Status", "DSC"):
                        patient_join_follow_up = (List<Tuple<Patient, Follow_Up_History>>)patient_join_follow_up
                            .OrderByDescending(s => s.Item2.Follow_Up.Status)
                            .ToList();
                        break;
                    case ("Status", "ASC"):
                        patient_join_follow_up = (List<Tuple<Patient, Follow_Up_History>>)patient_join_follow_up
                            .OrderBy(s => s.Item2.Follow_Up.Status)
                            .ToList();
                        break;
                    case ("Follow_Up", "DSC"):
                        patient_join_follow_up = (List<Tuple<Patient, Follow_Up_History>>)patient_join_follow_up
                            .OrderByDescending(s => s.Item2.Follow_Up_Type.Name)
                            .ToList();
                        break;
                    case ("Follow_Up", "ASC"):
                        patient_join_follow_up = (List<Tuple<Patient, Follow_Up_History>>)patient_join_follow_up
                            .OrderBy(s => s.Item2.Follow_Up_Type.Name)
                            .ToList();
                        break;
                    case ("Transfered", "DSC"):

To be delivered/Source Code/Views/Shared/_DoctorLayout.cshtml
@model Ain_Shams_Hospital.ViewModels.LogoutVM
@{ 
    var controller = @ViewContext.RouteData.Values["Controller"].ToString();

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Doctor</title>
    <link rel="icon" href="~/logo.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link href="~/css/doctor.css" rel="stylesheet" />
</head>
<body id="doctor">
    <header>
        <div style="background-color:#e7e7e7" class="container-fluid">
            <div class="row">
                <div class="container">
                    <div class="col-sm-9 float-left"><img id="Headimg" src="~/Images/ASH 4.png" height="66" /></div>
                    <p class="float-right" style="margin-right:20px;margin-top:5px;color:#0094ff;font-size:30px;font-weight:bold">19056</p>
                </div>

            </div>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Doctor" asp-action="Main">Home</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="btn btn-danger w-auto text-center float-left" href="Emergency" role="button">Emergency</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <form asp-controller="Registration" asp-action="Logout">
                                <button name="logout" type="submit" value="out" class="btn btn-dark mr-3">Log out</button>
                            </form>
                        </li>
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Schedule">My Schedules</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Profile">Profile</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>

    <main class="container pb-3" role="main">
        @RenderBody()
    </main>


    <footer class="border-top footer">
        <div class="text-center">
            &copy; 2020 - Ain Shams Hospital - Since 1980
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

To be delivered/Source Code/Views/Shared/_Layout.cshtml
@{
    var controller = @ViewContext.RouteData.Values["Controller"].ToString();

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/logo.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link href="~/css/Home.css" rel="stylesheet" />
    @if(controller == "Patient"){
        <link href="~/css/Patient.css" rel="stylesheet" />
    }
    @RenderSection("Styles", required: false)

</head>

<body>
    <header>
        <div style="background-color:#e7e7e7" class="container-fluid">
            <div class="row">
                <div class="container">
                    <div class="col-sm-9 float-left">
                        <img id="Headimg" src="~/Images/ASH 4.png" height="66" />
                    </div>
                    <p class="float-right" style="margin-right:20px;margin-top:5px;color:#0094ff;font-size:30px;font-weight:bold">
                        19056
                    </p>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if (controller != "Home" && controller != "Registration")
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <form asp-controller="Registration" asp-action="Logout">
                                    <button name="logout" type="submit" value="out" class="btn btn-dark">Log out</button>
                                </form>
                            </li>
                        </ul>
                    }

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    @*<div id="watermarkcont">
          <img id="watermark"src="~/Images/ASH B.png" />
        </div>*@
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted" style="background-color:#6da6cf">
        <div class="text-center">
            &copy; 2020 - Ain Shams Hospital - Since 1980
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Patient.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

To be delivered/Source Code/Views/Shared/_PatientLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Patient</title>
    <link rel="icon" href="~/logo.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/Home.css" rel="stylesheet" />
    <link href="~/css/Patient.css" rel="stylesheet" />
    <!-- timepicker -->
    <link href="~/lib/time-picker-bootstrap/timepicker.css" rel="stylesheet" />
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <!-- timepicker -->
    <script src="~/lib/time-picker-bootstrap/timepicker.js"></script>

</head>
<body>
    <header>
        <div style="background-color:#e7e7e7" class="container-fluid">
            <div class="row">
                <div class="container">
                    <div class="col-sm-9 float-left">
                        <img id="Headimg" src="~/Images/ASH 4.png" height="66" />
                    </div>
                    <p class="float-right" style="margin-right:20px;margin-top:5px;color:#0094ff;font-size:30px;font-weight:bold">
                        19056
                    </p>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Patient" asp-action="Home" style="font-weight: bold">Home</a>
 
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="FollowedDoctors" style="font-size:20px;color:#0026ff;font-weight:bold">Followed Doctors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="UserProfile" style="font-size:20px;color:#0026ff;font-weight:bold">My Profile</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-sm-column">
                        <li class="nav-item">
                            <form asp-controller="Registration" asp-action="Logout">
                                <button name="logout" type="submit" value="out" class="btn btn-dark">Log out</button>
                            </form>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>

    </header>
    @*<div id="watermarkcont">
          <img id="watermark"src="~/Images/ASH B.png" />
        </div>*@
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted" style="background-color:#6da6cf">
        <div class="text-center">
            &copy; 2020 - Ain Shams Hospital - Since 1980
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/time-picker-bootstrap/timepicker.js"></script>
    <script src="~/js/Patient.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>